Publisher Thread # put value into : Queue=[H, e, l, l, o]
Consumer Thread # remove value H from: Queue=[e, l, l, o]
Consumer Thread # remove value e from: Queue=[l, l, o]
Consumer Thread # remove value l from: Queue=[l, o]
Consumer Thread # remove value l from: Queue=[o]
Consumer Thread # remove value o from: Queue=[]
